(function(exports){
    var Class = require("./util").Class;
    var Items = {
	"0":{
            name:"母船",
            maxSpeed:1.2,
	    maxRotateSpeed:0.02,
            maxLife:6000,
            life:6000,
            level:0,
	    subType:"motherShip"
	    ,coolDown:60
	    ,size:50
	    ,range:100
	    ,attack:160
	    ,src:"motherShip"
	    ,consume:{
		mine:400
		,time:100
	    }
	},
	"1":{
            name:"矿船",
            maxSpeed:0.8,
	    maxRotateSpeed:0.08,
            maxLife:500,
            life:500,
            level:0, 
	    subType:"miningShip" 
	    ,curveForwarding:true
	    ,size:25
	    ,range:20
	    ,attack:50
	    ,coolDown:120
	    ,consume:{
		mine:500
		,time:300
	    }
	    ,src:"miningShip"
	},
	"2":{
            name:"哨兵",
            maxSpeed:3.2,
	    maxRotateSpeed:0.08,
	    coolDown:30,
            maxLife:150,
            life:150,
            level:0,
	    subType:"attackShip"
	    ,size:15
	    ,curveForwarding:true
	    ,attack:10
	    ,range:80
	    ,minSpeed:3
	    ,consume:{
		mine:300
		,time:150
	    }
	    ,src:"frontier"
	},
	"3":{
            name:"守护者",
            maxSpeed:2.4,
	    maxRotateSpeed:0.05,
	    coolDown:90,
            maxLife:950,
            life:950,
            level:0,
	    subType:"attackShip"
	    ,size:25
	    ,curveForwarding:true
	    ,attack:40
	    ,range:240
	    ,consume:{
		mine:900
		,time:240
	    }
	    ,src:"gardian"
	},"4":{
            name:"驱逐舰",
            maxSpeed:2.2,
	    maxRotateSpeed:0.06,
	    coolDown:60,
            maxLife:500,
            life:500,
            level:0,
	    subType:"attackShip"
	    ,size:25
	    ,curveForwarding:true
	    ,attack:120
	    ,range:150
	    ,consume:{
		mine:1200
		,time:300
	    }
	    ,src:"crusador"
	},"5":{
            name:"战列舰",
            maxSpeed:1.4,
	    maxRotateSpeed:0.05,
	    coolDown:120,
            maxLife:1800,
            life:1800,
            level:0,
	    subType:"attackShip"
	    ,size:35
	    ,curveForwarding:true
	    ,attack:300
	    ,range:170
	    ,consume:{
		mine:2500
		,time:600
	    }
	    ,src:"battleShip"
	    ,autoRecover:1 
	},"6":{
            name:"轻型工程舰",
            maxSpeed:2,
	    maxRotateSpeed:0.1,
	    coolDown:150,
            maxLife:500,
            life:500,
            level:0,
	    subType:"repairShip"
	    ,size:20
	    ,curveForwarding:true
	    ,attack:-80
	    ,range:100
	    ,consume:{
		mine:1400
		,time:300
	    }
	    ,src:"engineerShipLight"
	},"7":{
            name:"重型工程舰",
            maxSpeed:1.0,
	    maxRotateSpeed:0.04,
	    coolDown:210,
            maxLife:2000,
            life:2000,
            level:0,
	    subType:"repairShip"
	    ,size:45
	    ,curveForwarding:false
	    ,attack:-500
	    ,range:300
	    ,consume:{
		mine:4000
		,time:300
	    }
	    ,src:"engineerShipHeavy"
	}
    }
    GameResourceManager = Class.sub();
    GameResourceManager.prototype.load = function(items){
	this.items = items; 
    }
    GameResourceManager.prototype.get = function(id){
	return this.items[id];
    }
    exports.GameResourceManager = GameResourceManager;
    exports.Items = Items;
})(exports)
